http:
  listen_address: ":8080"

backends:
  # 在 docker 网络 assistant-net 中，通过服务名访问 account 容器。
  - name: "account"
    addr: "assistant-account-app:50051"

routes:
  - http_method: "POST"
    http_pattern: "/v1/user/login"
    backend_name: "account"
    backend_service: "user.v1.UserService"
    backend_method: "Login"
    timeout_ms: 1000
    request_type: "user.v1.LoginRequest"
    response_type: "user.v1.LoginResponse"


